env:
  MISE_EXPERIMENTAL: "true"

test_task:
  auto_cancellation: $CIRRUS_BRANCH != 'main'
  timeout_in: 10m
  container:
    image: ghcr.io/jdx/mise:latest
  mise_cache:
    folder: .mise
    fingerprint_script: cat mise.toml mise.lock
    populate_script: mise install
  test_script:
    - mise run test

release_task:
  only_if: $CIRRUS_TAG != '' || $CIRRUS_BRANCH == 'main'
  depends_on: test
  timeout_in: 10m
  container:
    image: ghcr.io/jdx/mise:latest
  env:
    GH_TOKEN: ENCRYPTED[TODO]
  mise_cache:
    folder: .mise
    fingerprint_script: cat mise.toml mise.lock
    populate_script: mise install
  release_script:
    - mise run do-all
    - mise exec -- elixir version-info.exs
