env:
  MISE_EXPERIMENTAL: "true"
  MISE_DATA_DIR: /tmp/cirrus-ci-build/.mise

test_task:
  auto_cancellation: $CIRRUS_BRANCH != 'main'
  container:
    image: ghcr.io/jdx/mise:latest
  mise_cache:
    folder: .mise
    fingerprint_script: cat mise.toml mise.lock
    populate_script: mise install
  hex_cache:
    folder: .mise-hex
    fingerprint_script: cat mise.toml
  mix_home_cache:
    folder: .mise-mix
    fingerprint_script: cat mise.toml
  deps_cache:
    folder: deps
    fingerprint_script: cat mix.lock
  build_cache:
    folder: _build
    fingerprint_script: cat mix.lock
  test_script:
    - mise run test

release_task:
  only_if: $CIRRUS_TAG != '' || $CIRRUS_BRANCH == 'main'
  depends_on: test
  timeout_in: 10m
  container:
    image: ghcr.io/jdx/mise:latest
  env:
    GH_TOKEN: ENCRYPTED[TODO]
  mise_cache:
    folder: .mise
    fingerprint_script: cat mise.toml mise.lock
    populate_script: mise install
  hex_cache:
    folder: .mise-hex
    fingerprint_script: cat mise.toml
  mix_home_cache:
    folder: .mise-mix
    fingerprint_script: cat mise.toml
  deps_cache:
    folder: deps
    fingerprint_script: cat mix.lock
  build_cache:
    folder: _build
    fingerprint_script: cat mix.lock
  release_script:
    - mise run do-all
    - mise exec -- elixir version-info.exs
