require Logger

Logger.info("Markdown files in path:\n\n#{Path.wildcard("images/*.md") |> Enum.join("\n")}")

markdown_files = [

"images/aws-sso-config-generator-authorization-code-pkce-flow.md",
"images/aws-sso-auth-code-pkce-flow.md",
"images/aws-sso-config-generator-device-code-flow.md",
"images/aws-sso-device-code-flow.md",] |> Enum.map(fn file -> "#" <> File.read!(file) end)

["# aws-sso-config-generator images\n", "This is generated by [build-images-readme.exs](./build-images-readme.exs).\n"] ++ markdown_files
|>Enum.join("\n") |> then(& File.write("images/README.md", &1))
