name: main
on:
  push:
    branches:
      - main
env:
  DEVBOX_API_TOKEN: ${{ secrets.DEVBOX_API_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'djgoku'
    steps:
      - uses: actions/checkout@v4
      - name: Install devbox with empty devbox.json
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: 'true'
      - name: upload release artifacts
        run: |
          set -x
          devbox run do-all
          devbox run version-info
