on:
  workflow_dispatch:
  push:
    tags: ["*"]
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true
  DEVBOX_API_TOKEN: ${{ secrets.DEVBOX_API_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install devbox with empty devbox.json
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: 'true'
      - name: build and upload release artifacts
        uses: jdx/mise-action@v2
      - run: |
          devbox run -- mise run do-all
          mise exec -- elixir version-info.exs
